version: '3.8'
services:
  app:
    build: ./BackEnd
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/delivery
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: your_password

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: delivery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  
  frontend:
    build: ./frontend/client
    ports:
      - "4200:8080"
    depends_on:
      - app

volumes:
  db-data:
